gt_path: /home/junetheriver/code/aiops/data/groundtruth_b.xlsx
dt_raw: /home/junetheriver/code/aiops/data/system-b/
seed: 0
workdir: /home/junetheriver/code/aiops/workdir/system_b
start_time: 1614700800

conv: (128,4,1,0)
nso: 64

wstart: -2
window: 10
tag: "w=(-2,10),stat"
model: Stat
show_fail: True
epoch: 200